### ISSUE TITLE
Remove installpath for `cborm`

### ISSUE THREAD

**Issue by jclausen** [coldbox-modules/cborm-versioning#1]
Module `installPaths` are predefined in delivered module:

```
 "installPaths":{
        "testbox":"testbox",
        "coldbox":"tests/resources/app/coldbox",
        "cborm":"modules/cborm"
    },
```

Having an `installPaths` specified for `cborm` in your module's `box.json` means that an additional copy of it will be installed in the modules `modules/` directory, regardless of whether the dependency already is fulfilled.  Omitting that key from your Module's file will allow the previously fulfilled dependency to be used.

**Comment by elpete** [comment]
What if the dependency has not been filled?

**Comment by jclausen** [comment]
Then it will be installed in the modules subdirectory of the module.


On May 4, 2017, at 6:08 PM, Eric Peterson <notifications@github.com<mailto:notifications@github.com>> wrote:


What if the dependency has not been filled?
